# Generated by Django 4.2.13 on 2024-06-05 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInfo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ja', models.CharField(max_length=255)),
                ('name_zn', models.CharField(max_length=255)),
                ('image_ko', models.ImageField(upload_to='images/')),
                ('image_en', models.ImageField(upload_to='images/')),
                ('image_ja', models.ImageField(upload_to='images/')),
                ('image_zn', models.ImageField(upload_to='images/')),
                ('bookmark_count', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ko', 'Korean'), ('zh', 'Chinese'), ('ja', 'Japanese')], default='en', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('restaurant_name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('username', 'restaurant_name')},
            },
        ),
    ]
