# Generated by Django 4.2.13 on 2024-06-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantinfo1',
            name='image_en',
            field=models.ImageField(upload_to='images_en/'),
        ),
        migrations.AlterField(
            model_name='restaurantinfo1',
            name='image_ja',
            field=models.ImageField(upload_to='images_ja/'),
        ),
        migrations.AlterField(
            model_name='restaurantinfo1',
            name='image_ko',
            field=models.ImageField(upload_to='images_ko/'),
        ),
        migrations.AlterField(
            model_name='restaurantinfo1',
            name='image_zn',
            field=models.ImageField(upload_to='images_zn/'),
        ),
    ]
