# Generated by Django 4.2.13 on 2024-06-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebot', '0003_alter_restaurantinfo1_image_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantinfo1',
            old_name='image_zn',
            new_name='image_zh',
        ),
        migrations.RenameField(
            model_name='restaurantinfo1',
            old_name='name_zn',
            new_name='name_zh',
        ),
    ]
